//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsLayoutSnapshot.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[\"{\\\"name\\\":\\\"test\\\",\\\"processList\\\":{\\\"199222\\\":{\\\"position\\\":\\\"-8, -8, 1936, 10" +
            "48\\\",\\\"visible\\\":\\\"-1, -8, 1922, 1041\\\",\\\"title\\\":\\\"WindowsLayoutSnapshot (Exécu" +
            "tion) - Microsoft Visual Studio\\\",\\\"processPath\\\":\\\"D:\\\\\\\\visuql studio\\\\\\\\Commo" +
            "n7\\\\\\\\IDE\\\\\\\\devenv.exe\\\"},\\\"2231142\\\":{\\\"position\\\":\\\"0, 1, 911, 683\\\",\\\"visibl" +
            "e\\\":\\\"0, 1, 911, 683\\\",\\\"title\\\":\\\"Paramètres\\\",\\\"processPath\\\":\\\"C:\\\\\\\\Windows\\" +
            "\\\\\\ImmersiveControlPanel\\\\\\\\SystemSettings.exe\\\"},\\\"4787044\\\":{\\\"position\\\":\\\"16" +
            "4, 243, 927, 692\\\",\\\"visible\\\":\\\"171, 243, 913, 685\\\",\\\"title\\\":\\\"Paramètres\\\",\\" +
            "\"processPath\\\":\\\"C:\\\\\\\\WINDOWS\\\\\\\\system32\\\\\\\\ApplicationFrameHost.exe\\\"},\\\"7889" +
            "44\\\":{\\\"position\\\":\\\"-8, -8, 1936, 1048\\\",\\\"visible\\\":\\\"-8, -8, 1936, 1048\\\",\\\"t" +
            "itle\\\":\\\"To Do — Firefox Developer Edition\\\",\\\"processPath\\\":\\\"C:\\\\\\\\Program Fil" +
            "es\\\\\\\\Firefox Developer Edition\\\\\\\\firefox.exe\\\"},\\\"14551346\\\":{\\\"position\\\":\\\"1" +
            "912, -8, 1936, 1048\\\",\\\"visible\\\":\\\"1919, -8, 1922, 1041\\\",\\\"title\\\":\\\"OBS 28.1." +
            "2 (64-bit, windows) - Profil: Stream - Scènes: Mira\\\",\\\"processPath\\\":\\\"C:\\\\\\\\Pr" +
            "ogram Files\\\\\\\\obs-studio\\\\\\\\bin\\\\\\\\64bit\\\\\\\\obs64.exe\\\"},\\\"132526\\\":{\\\"position" +
            "\\\":\\\"-1015, 630, 940, 720\\\",\\\"visible\\\":\\\"-1015, 630, 940, 720\\\",\\\"title\\\":\\\"#me" +
            " | Quentin / Mirardes - Discord\\\",\\\"processPath\\\":\\\"C:\\\\\\\\Users\\\\\\\\Admin\\\\\\\\AppD" +
            "ata\\\\\\\\Local\\\\\\\\Discord\\\\\\\\app-1.0.9007\\\\\\\\Discord.exe\\\"},\\\"66962\\\":{\\\"position\\" +
            "\":\\\"-1049, -418, 1056, 600\\\",\\\"visible\\\":\\\"-1049, -418, 1056, 600\\\",\\\"title\\\":\\\"" +
            "Plusma - Parasol\\\",\\\"processPath\\\":\\\"C:\\\\\\\\Users\\\\\\\\Admin\\\\\\\\AppData\\\\\\\\Roaming\\" +
            "\\\\\\Spotify\\\\\\\\Spotify.exe\\\"},\\\"329928\\\":{\\\"position\\\":\\\"-1061, 201, 413, 334\\\",\\" +
            "\"visible\\\":\\\"-1054, 201, 399, 327\\\",\\\"title\\\":\\\"Current Song by LeStudio (v1.0.2" +
            ")\\\",\\\"processPath\\\":\\\"C:\\\\\\\\Users\\\\\\\\Admin\\\\\\\\Documents\\\\\\\\LeStudioCurrentSong\\\\" +
            "\\\\LeStudioCurrentSong.exe\\\"},\\\"68256\\\":{\\\"position\\\":\\\"-1080, -452, 1080, 1872\\\"" +
            ",\\\"visible\\\":\\\"-1073, -452, 1066, 1865\\\",\\\"title\\\":\\\"\\\",\\\"processPath\\\":\\\"C:\\\\\\\\" +
            "WINDOWS\\\\\\\\Explorer.EXE\\\"},\\\"67460\\\":{\\\"position\\\":\\\"-8, -8, 1936, 1048\\\",\\\"visi" +
            "ble\\\":\\\"-1, -8, 1922, 1041\\\",\\\"title\\\":\\\"Xbox\\\",\\\"processPath\\\":\\\"C:\\\\\\\\WINDOWS\\" +
            "\\\\\\system32\\\\\\\\ApplicationFrameHost.exe\\\"},\\\"133386\\\":{\\\"position\\\":\\\"0, 0, 1920" +
            ", 1032\\\",\\\"visible\\\":\\\"7, 0, 1906, 1025\\\",\\\"title\\\":\\\"\\\",\\\"processPath\\\":\\\"C:\\\\\\" +
            "\\WINDOWS\\\\\\\\Explorer.EXE\\\"},\\\"131554\\\":{\\\"position\\\":\\\"1920, 0, 1920, 1032\\\",\\\"v" +
            "isible\\\":\\\"1927, 0, 1906, 1025\\\",\\\"title\\\":\\\"\\\",\\\"processPath\\\":\\\"C:\\\\\\\\WINDOWS\\" +
            "\\\\\\Explorer.EXE\\\"},\\\"131680\\\":{\\\"position\\\":\\\"0, 0, 1920, 1080\\\",\\\"visible\\\":\\\"0" +
            ", 0, 1920, 1080\\\",\\\"title\\\":\\\"Expérience d’entrée Windows\\\",\\\"processPath\\\":\\\"C:" +
            "\\\\\\\\WINDOWS\\\\\\\\SystemApps\\\\\\\\MicrosoftWindows.Client.CBS_cw5n1h2txyewy\\\\\\\\TextIn" +
            "putHost.exe\\\"},\\\"198642\\\":{\\\"position\\\":\\\"-32000, -32000, 160, 28\\\",\\\"visible\\\":" +
            "\\\"-32000, -32000, 160, 28\\\",\\\"title\\\":\\\"VoiceMeeter\\\",\\\"processPath\\\":\\\"C:\\\\\\\\Pr" +
            "ogram Files (x86)\\\\\\\\VB\\\\\\\\Voicemeeter\\\\\\\\voicemeeterpro.exe\\\"},\\\"68518\\\":{\\\"pos" +
            "ition\\\":\\\"-32000, -32000, 160, 28\\\",\\\"visible\\\":\\\"-31993, -32000, 146, 21\\\",\\\"ti" +
            "tle\\\":\\\"LeStudio App - Google Chrome\\\",\\\"processPath\\\":\\\"C:\\\\\\\\Program Files\\\\\\\\" +
            "Google\\\\\\\\Chrome\\\\\\\\Application\\\\\\\\chrome.exe\\\"}}}\"]\r\n")]
        public string savedConfigurations {
            get {
                return ((string)(this["savedConfigurations"]));
            }
            set {
                this["savedConfigurations"] = value;
            }
        }
    }
}
